name: CI/CD

on:
  push:
    branches: [ "main" ]
    workflow_dispatch:   # allow manual trigger
  pull_request:
    branches: [ "dev" ]


permissions:
  contents: read
  packages: write

jobs:
  build_push_and_deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}   # ✅ set once here

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger Render deploy
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Smoke check (optional)
        if: env.DEPLOY_URL != ''    # ✅ check env, not secrets
        run: |
          echo "⏳ Waiting for app to boot…"
          sleep 15
          curl -fsS "$DEPLOY_URL/health" || exit 1
